services:
  api:
    build: ./backend
    ports:
    - "8080:8080"
    volumes:
    - ./backend:/app
    image: server_flask_back
  client:
    build: ./frontend/
    ports:
    - "3000:3000"
    volumes:
    - ./frontend:/app
    image: client_react_front