services:
  api:
    build: ./backend
    ports:
    - "8080:8080"
    volumes:
    - ./backend:/app
    image: audzdocker99710/flaskapi_final
  client:
    build: ./frontend/
    ports:
    - "3000:3000"
    volumes:
    - ./frontend:/app
    image: audzdocker99710/react_front